# Generated by Django 3.2.15 on 2022-09-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the accounting provider.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the business.', max_length=200)),
                ('loan_amount', models.FloatField(default=0.0, help_text='Amount requested by this business in Australian dollars.')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_sheet', models.JSONField(default=list, help_text='Current accounting balance for this business with this accounting provider.')),
                ('accounting_provider', models.ForeignKey(help_text='Name of the accounting provider.', on_delete=django.db.models.deletion.CASCADE, to='businessloanapp.accountingprovider')),
                ('business', models.ForeignKey(help_text='Business this balance sheet belongs to.', on_delete=django.db.models.deletion.CASCADE, to='businessloanapp.business')),
            ],
        ),
    ]
